name: Run Tests

on:
  schedule:
    - cron:'13 03 * * *' #IST=UTC+5.30

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install -r requirements.txt

      - run: playwright install chromium --with-deps

      - run: pytest

